version: '3'

services: 
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 45253:45253
    environment:
      - API_LOCATION=http://localhost:3001
    networks:
      - default

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:  
      - NODE_URI=0.0.0.0
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=lorem
      - PGDATABASE=tracking
      - DBPORT=5432
      - NODE_ENV=dev
    ports:
      - 3001:3001
    networks:
      - default
    command: npm run dev
    depends_on:
      - db
    
  db:
    image: postgres:latest
    environment: 
      - POSTGRES_DB=tracking
      - POSTGRES_PASSWORD=lorem
    volumes: 
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - default
networks:
  default: